name: Deploy Challenge Platinum Project

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/mock-test
            git pull origin master
            docker compose down
            docker rmi mock-test_mock_test_app:latest
            docker rmi mock-test_mock_db_migration:latest
            docker compose up -d --build