name: Node.js CI/CD

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/mock-test
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git fetch --all 
            git reset --hard origin/master
            git pull origin master
            git status
            npm install
            npm run db:migrate:prod
            npm run start